# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Testing-CI-CD ]
  pull_request:
    branches: [ Testing-CI-CD ]

env:
  QT_VERSION: 5.12.8

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        # Architecture for Windows/Android
        arch: x64
        version: $ENV{QT_VERSION}
        # Force a Qt mirror in case the default is not working
        mirror: true
        cached: true
        dir:    $ENV{GITHUB_WORKSPACE}/Qt
        
    - name: Getting paths
      id:   paths
      shell: bash
      run: |
        export qt_version=$QT_VERSION
        export qt_dir_prefix="$qt_version/gcc_64"
        ls $GITHUB_WORKSPACE
        ls .
        export qt_dir=Qt/Qt$qt_version/$qt_dir_prefix
        echo $qt_dir
        ls  $qt_dir

    # Runs a set of commands using the runners shell
    - name: QMake project
      shell: bash
      run: $qt_dir/bin/qmake AdvancedLibraryCpp.pro -spec linux-clang CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info && /usr/bin/make qmake_all

    - name: clean 
      shell: bash
      run: make clean -j8
      
    - name: make
      shell: bash
      run: make -j8
      
    - name: Running tests
      shell: bash
      run:  AdvancedLibraryCpp/binaries/linux/clang/x64/release/tests
      
      
      
